[package]
name = "pathfix"
description = "Fixes the $PATH variable mess by generating it for you"
version = "0.1.0"
authors = ["Raphael Peters <rappet@rappet.de>"]
edition = "2018"
readme = "README.md"
license = "GPL-3.0"
repository = "https://github.com/rappet/pathfix"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~2.33.1", features = ["yaml"] }
serde = { version = "~1.0", features = ["derive"] }
serde_yaml = "0.8"

[profile.release]
lto = true
